/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
	// By default, Docusaurus generates a sidebar from the docs folder structure
	// tutorialSidebar: [{ type: "autogenerated", dirName: "." }],
	// But you can create a sidebar manually
	projectsSidebar: [
		{
			type: "category",
			label: "Projecten",
			link: {
				type: "generated-index",
				title: "Projecten",
				description:
					"Een highlight van interessante projecten waaraan iTVDB heeft kunnen meewerken",
			},
			items: [
				{
					type: "autogenerated",
					dirName: "projects",
				},
			],
		},
	],
	teamSidebar: [
		{
			type: "category",
			label: "Team",
			link: {
				type: "generated-index",
				title: "Het team",
			},
			items: [{ type: "autogenerated", dirName: "team" }],
		},
	],
	netwerkSidebar: [
		{
			type: "category",
			label: "Netwerk",
			link: {
				type: "generated-index",
				title: "Netwerk in de kijker",
				description:
					"Een netwerk van onschatbare waarde van informatie, kennis en contacten. Zonder hun zou ik niet staan waar ik vandaag sta",
			},
			items: [{ type: "autogenerated", dirName: "netwerk" }],
		},
	],
};

module.exports = sidebars;
